[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = [".gitignore", "algorithms/sorting/Bubble_sort.py", "algorithms/sorting/selection_sort.py", "form.ui", "main.py", "visualizer/Searching_visualizer.py", "visualizer/Sorting_viz", "visualizer/Sorting_viz/InsertionSort_visualizer.py", "visualizer/Sorting_viz/SelectionSort_visualizer.py", "visualizer/Stack_visualizer.py", "visualizer/searching_viz/BinarySearch_visualizer.py", "visualizer/sorting_visualizer.py", "widget.py"]
